#!/usr/bin/env python3
"""Regenerate .design-sync/shims/ambiguous-reexports.ts.

ESM drops names star-exported from more than one file, so components exported
by two source files vanish from window.<globalName>. This script finds every
such name, picks a canonical source file, and emits a shim that re-imports each
name explicitly and patches it onto the global one tick after bundle init.
Run from the repo root; pass the missing-name list on stdin (one per line).
"""
import re, sys, glob, os, json

missing = [l.strip() for l in sys.stdin if l.strip()]
decl = {}
rx_cache = {n: re.compile(
    r'export\s+(?:default\s+)?(?:async\s+)?(?:function|const|class|let|var)\s+' + n + r'\b'
    ) for n in missing}
rx_brace = re.compile(r'export\s*\{([^}]*)\}')
for f in glob.glob('components/**/*.tsx', recursive=True) + glob.glob('components/**/*.ts', recursive=True):
    if re.search(r'\.(test|spec|stories)\.', f): continue
    try: text = open(f, encoding='utf8', errors='ignore').read()
    except OSError: continue
    for n in missing:
        hit = bool(rx_cache[n].search(text))
        if not hit:
            for m in rx_brace.finditer(text):
                names = [p.split(' as ')[-1].strip() for p in m.group(1).split(',')]
                if n in names: hit = True; break
        if hit: decl.setdefault(n, []).append(f)

def pick(n, files):
    ui = [f for f in files if f.startswith('components/ui/')]
    if len(ui) == 1: return ui[0]
    named = [f for f in files if os.path.splitext(os.path.basename(f))[0].lower()
             in (n.lower(), re.sub(r'([a-z0-9])([A-Z])', r'\1-\2', n).lower())]
    if len(named) == 1: return named[0]
    if named: return sorted(named)[0]
    return sorted(files, key=lambda f: (len(f), f))[0]

lines = ["// AUTO-GENERATED by .design-sync/gen-ambiguous-shim.py — do not hand-edit.",
         "// Explicit imports of names ESM drops as ambiguous star re-exports; patched",
         "// onto the global one tick after the bundle footer runs."]
imports, patch_names, report = [], [], {}
for n in sorted(missing):
    files = decl.get(n)
    if not files:
        report[n] = 'NO DECLARATION FOUND — skipped'; continue
    src = pick(n, files)
    report[n] = {'chosen': src, 'all': files} if len(files) > 1 else {'only': src}
    text = open(src, encoding='utf8', errors='ignore').read()
    mod = '../../' + (src[:-4] if src.endswith('.tsx') else src[:-3])
    has_named = re.search(r'export\s+(?:async\s+)?(?:function|const|class|let|var)\s+' + n + r'\b', text) or \
        any(n in [q.split(' as ')[-1].strip() for q in m.group(1).split(',')]
            for m in rx_brace.finditer(text))
    has_default = re.search(r'export\s+default\b', text)
    if has_named:
        imports.append(f"import {{ {n} as _{n} }} from '{mod}';")
    elif has_default:
        imports.append(f"import _{n} from '{mod}';")
        report[n]['import'] = 'default'
    else:
        report[n] = 'NO usable export — skipped'; continue
    patch_names.append(n)
lines += imports
lines.append("const __patch: Record<string, unknown> = { " + ", ".join(f"{n}: _{n}" for n in patch_names) + " };")
lines.append("""let __tries = 0;
const __apply = () => {
  const g: any = (globalThis as any).TatFinderDS;
  if (g) { for (const k of Object.keys(__patch)) if (g[k] === undefined) g[k] = __patch[k]; }
  else if (++__tries < 50) setTimeout(__apply, 10);
};
setTimeout(__apply, 0);
export const dsAmbiguousReexports = true;""")
open('.design-sync/shims/ambiguous-reexports.ts', 'w').write("\n".join(lines) + "\n")
json.dump(report, open('.design-sync/.cache/ambiguous-report.json', 'w'), indent=1)
multi = {n: r for n, r in report.items() if isinstance(r, dict) and 'all' in r}
print(f"patched {len(patch_names)}/{len(missing)}; {len(multi)} had multiple declarations")
for n, r in list(multi.items())[:12]: print(' ', n, '->', r['chosen'], f"(of {len(r['all'])})")
